name: lessons
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  lottie: ^3.3.2
  provider: ^6.1.5+1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  liquid_glass_ui: ^0.4.0
  build_runner: ^2.13.1
  freezed: ^3.2.5
  json_serializable: ^6.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
